# Generated by Django 5.1.5 on 2025-04-24 18:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='plant_scans/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('completed', 'Analysis Completed'), ('failed', 'Analysis Failed')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(blank=True, max_length=200, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('diagnosis_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('plant_scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='plant_scans.plantscan')),
            ],
        ),
    ]
